### ISSUE TITLE
Update Packagedb with latest ScanCode Toolkit with package models and license detection support

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#11]
SCTK is about to be released and we need to align packagedb, mining and matching accordingly

**Comment by JonoYang** [comment]
@pombredanne 

I'm wondering how Package dependencies should be handled on purldb. In scancode-toolkit, Package data in the top-level codebase attributes do not include dependency data, as dependencies are reported in their own section. In the PackageDB, we return dependencies with Package data, similar to how we report Resource-level Package data in scancode-toolkit. 

Should we include dependency data in Package data or separate them like we do with scancode-toolkit? I am in favor of keeping the dependency data with the package data for convenience.

**Comment by JonoYang** [comment]
Purldb models and other code has been updated work with the latest version of scancode-toolkit.
