### ISSUE TITLE
Server-side matchcode processing

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#224]
We want to run the entire matchcode process from the server side, instead of having the client-server setup we have with scancode.io and purldb. This involves integrating scio and purldb together and updating the matching pipeline to not use API calls but directly accessing the purldb models.

We have a purldb and scancode.io app that cooperate:
- "client" scancode.io is where a user creates a project and codebase and requests a matching pipeline. This pipeline will post a scan to the server, check if the match is done, and then process match results when available.
- "server" scancode.io, that we call matchcode, receives a POST request from the scancode.io client with codebase scan
- matchcode runs a pipeline that performs Package matching on the purldb

The new matching endpoint will be at `/api/matching` POST
    a. Request:
        - ScanCode scan
        - Webhook
    b. Response:
        - Matching-id if matching is successfully started else error message
    c. Call the webhook with enhanced scan result
    d. /api/matching/<matching-id> - Shows the status and result of match instance
    
  
- [x] #273 and https://github.com/nexB/scancode.io/pull/1042
- [x] Create a server matching pipeline on purldb/matchcode. This is the main issue for #224
- [x] Create API endpoint for matching. This is the new "matchode.io" API endpoint.
- [x] Configure access to purldb from matchcode. This is using two databases and a database router.
- [ ] #274
- [ ] #275

**Comment by pombredanne** [comment]
Closing in favor of the duplicated #238
