### ISSUE TITLE
Collect Debian data live, aka. purl2meta

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#245]
I would like to have the live, on demand PurlDB API endpoint for metadata and scans to support for live, synchronous collection of a system/distro ecosystem for Debian distro packages (And later we can expand this to other distros):

The design would include updated API end-point(s) for metadata and scan for Debian packages (aka. purl2meta and purl2scancode)
- [x] Update ScanCode toolkit and libs to correctly collect Debian package details
  - [x] https://github.com/nexB/scancode-toolkit/pull/3647
  - [x] https://github.com/nexB/scancode-toolkit/pull/3661
  - [x] https://github.com/nexB/debian-inspector/pull/36
  - [x] https://github.com/nexB/scancode-toolkit/pull/3682
- [x] Update ScanCode.io to use the updated toolkit https://github.com/nexB/scancode.io/pull/1096
  
- [x] Update API endpoint to accept a Debian PURL input and return live metadata for this Debian package.
- [x] Update API endpoint to accept a Debian PURL input and return live scancode results for the corresponding Debian package. https://github.com/nexB/scancode.io/issues/1110

**Comment by pombredanne** [comment]
A simple use case is that given an container image scan in SCIO, we should be able to metadata from Debian for all its PURLs.

**Comment by AyanSinhaMahapatra** [comment]
Yes, this is completed, and also merged and released everywhere else (SCTK, SCIO and debian-inspector) to be included in purldb.


In `debian-inspector` (released as [v31.1.0](https://github.com/nexB/debian-inspector/releases/tag/v31.1.0)):
* https://github.com/nexB/debian-inspector/pull/36 Added support for parsing specific metadata files for purls and other improvements in parsing debian .dsc, copyright and changelog files used to get metadata.

In `scancode-toolkit` (released as [v32.1.0](https://github.com/nexB/scancode-toolkit/releases/tag/v32.1.0)):
* Improve debian source/binary package detection [nexB/scancode-toolkit#3682](https://github.com/nexB/scancode-toolkit/pull/3682): 
   - added debian namespace detection from clues and correct namespace based on other detected packages.
   - use changes in debian-inspector`  v31.1.0
   - fix purl qualifier bugs
   - support scanning .dsc and copyright files and improving debian source/binary scan results for SCIO pipelines

* Get debian source purl from parsing debian status files [nexB/scancode-toolkit#3661](https://github.com/nexB/scancode-toolkit/pull/3661)

In `scancode.io` (released as [v34.1.0](https://github.com/nexB/scancode.io/releases/tag/v34.1.0)):
* update debian support https://github.com/nexB/scancode.io/pull/1096:
   - Add support for sending source purls for debian packages in populate_purldb pipeline
   - Add debian namespace from debian distro info detected
   - use latest SCTK v32.1.0

* Purldb: https://github.com/nexB/purldb/pull/300/
   - update collect/ endpoints and all related functionality to accept and use source purls with purls
   - get debian binary, source package links, metadata .dsc and copyright links from purl and source purls (just purl would not be sufficient)
   - support both debian and ubuntu packages

We also have the latest SCTK and SCIO releases with all these changes merged in purldb: https://github.com/nexB/purldb/pull/357

See also https://github.com/nexB/purldb/issues/242 and https://github.com/nexB/scancode.io/issues/1110 for related support to fetch metadata and get scancode scans.

To test this out:
1. You can either provide debian PackageURLs from debian/ubuntu docker images or scan the latest debian docker images https://scancodeio.readthedocs.io/en/latest/tutorial_web_ui_analyze_docker_image.html
2. You can either send individual purls to the `api/collect/purl?=` endpoint or use the [populate purldb pipeline ](https://github.com/nexB/scancode.io/blob/main/scanpipe/pipelines/populate_purldb.py) to send these purls to purldb to get the metadata, or collect and store both metadata and scan binary/source packages.

This is tested end-to-end and working nicely for all the debian purls in ubuntu and debian latest docker images.
