### ISSUE TITLE
Create new PURL services

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#246]
I would like to have various small API services all keyed by PURL, either as new endpoints or extending existing endpoints, with backing ScanCode.io pipelines as needed:

- [x] #259
- [x] #258
- [x] #260

**Comment by pombredanne** [comment]
Let's design a suite of rest API PURL-related endpoints that that are easy to understand:
- 1. we have things that take a PURL as an input and return data:
  - we have "validate": at "https://<host>/api/validate/" use PURL as an input
  - DWARF and Git use PURL as an input. A symbols endpoint would use this in the future too.

- 2. we have things that take a some other data as an input and return PURLs:
  - Go use a Go import as an input and returns PURLs
  - we would need also something that exposes a url2purl taking a URL as input and returns PURLs
  - we could also have a GitHub, GitLab or other VCS URL input and return all the tags (e.g., we could return PURLs too) 

- For 1. we should group these services under some "from_purl" header as they take a PURL as an input
  - `from_purl/validate`
  - `from_purl/dwarf`
  - `from_purl/urls`
  - `from_purl/versions`
  - `from_purl/git`
  
- For 2. we should group these services under some "to_purl" header as they return PURLs
  - `to_purl/url`
  - `to_purl/go_import`

**Comment by DennisClark** [comment]
@pombredanne  @TG1999   I believe that this can be closed, since the 3 task issues are all done, with comments to describe how they can be tested.

**Comment by pombredanne** [comment]
See for completion details:
- https://github.com/nexB/purldb/issues/259#issuecomment-1997515580
- https://github.com/nexB/purldb/issues/258#issuecomment-2000133849
- https://github.com/nexB/purldb/issues/260#issuecomment-2025649998
