### ISSUE TITLE
purl2git: From PURL get Git versions and tags 

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#258]
Create a PURL service that returns a new PURL for the corresponding git repos and the tag matching the PURL provided version. This should be implemented for now for Maven, npm and Debian package types. (And later for all packages)

**Comment by pombredanne** [comment]
Based on https://github.com/nexB/purldb/issues/246#issuecomment-1953970478 we would have a new `from_purl/git` API endpoint

**Comment by TG1999** [comment]
This is done. We now have:

- an endpoint `/api/from_purl/purl2git` to get a git repo url from a valid package url string. 

This PR has been merged
- https://github.com/nexB/purldb/pull/299

To test this feature:

- Install PurlDB from the main branch
- Make a request to `/api/from_purl/purl2git?package_url={package_url}` where package_url is a valid package url string

**Comment by pombredanne** [comment]
For reference, I had also these notes:

- To support the purl2git service we created the core functions that can find a a git repository and can then find the set of tags to match these to a version. 

- We used a management command that can take a CSV list of source repositories and creates the corresponding packages (adding them in the corresponding set as needed) https://github.com/nexB/purldb/blob/main/packagedb/management/commands/create_source_repo_packages.py

- We also iterated on a script to find the corresponding git source repository of package using various heuristics: https://github.com/nexB/purldb/blob/main/packagedb/find_source_repo.py  
- This yields decent results when running at scale on many packages, in particular Java and JavaScript npm
