### ISSUE TITLE
Do not force/enable ScanAndFingerprintPackage pipeline by default

### ISSUE THREAD

**Issue by tdruez** [nexB/purldb#263]
https://github.com/nexB/purldb/blob/fa6b38e46f5ba5ec631cf8b2b1ee982dc2171471/matchcode-toolkit/setup.cfg#L69

As  `matchcode-toolkit` is a dependency of ScanCode.io, this pipeline is always enabled by default and cannot be easily disabled.
It should instead be enable only when needed for a given SCIO instance.

The current setup is also problematic as ScanAndFingerprintPackage is a subclass of ScanPackage making it complicated to make some changes there without breaking the entire SCIO.

For example, in the context of https://github.com/nexB/scancode.io/pull/1031 , we cannot rename some of the steps:

```
 python3.10/site-packages/matchcode_toolkit/pipelines/scan_and_fingerprint_package.py", line 38, in steps
    cls.get_package_archive_input,
AttributeError: type object 'ScanAndFingerprintPackage' has no attribute 'get_package_archive_input'
```

**Comment by JonoYang** [comment]
@tdruez I've created a new release of matchcode-toolkit where I removed the ScanAndFingerprintPackage pipeline from the entrypoints. I've also created a PR on scancode.io to bump the version: https://github.com/nexB/scancode.io/pull/1032

**Comment by tdruez** [comment]
@JonoYang Thanks, added in https://github.com/nexB/scancode.io/pull/1031

**Comment by tdruez** [comment]
@JonoYang Thanks! Could you update the `ScanAndFingerprintPackage` to work with the changes from https://github.com/nexB/scancode.io/pull/1031/files#diff-91090dfa30bc215ac2d0e47c8fc82256c6eb49d4940f813825de54883ef44188

**Comment by JonoYang** [comment]
@tdruez I've updated the pipeline and created a new release of matchcode-toolkit for it. I've also created a PR at scancode.io to bump the matchcode-toolkit version: https://github.com/nexB/scancode.io/pull/1033
