### ISSUE TITLE
Value for namespace is missing in purls generated for npms

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#264]
There is a package in https://public.purldb.io/  that appears to have an incomplete purl value. 

Package URL
pkg:npm/deep-equal@2.2.1
Filename
deep-equal-2.2.1.tgz
Download URL
https://registry.npmjs.org/deep-equal/-/deep-equal-2.2.1.tgz

Shouldn't the correct Package URL value be 
pkg:npm/registry.npmjs.org/deep-equal@2.2.1
?

or am I not understanding what should be there?   this appears to be a pattern for a number of npm packages in the PurlDB.

**Comment by JonoYang** [comment]
The purl value for `deep-equal v2.2.1` looks correct to me. The purl spec says that the namespace field for the scope of the npm packages: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#npm

**Comment by DennisClark** [comment]
ok, thanks for the explanation
