### ISSUE TITLE
Create client matching pipeline on scancode.io

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#273]
This happens in https://github.com/nexB/scancode.io/pull/1042

**Comment by JonoYang** [comment]
This is complete as https://github.com/nexB/scancode.io/pull/1042 has been merged.

**Comment by pombredanne** [comment]
This is done. We now have 
- An updated PurlDB that exposes its indexing and scan queue as a service (using an API endpoint).  The code for the new scan queue was merged with https://github.com/nexB/purldb/pull/290 

- A wrapper a ScanCode.io instance to behave as a worker that will be polling the PurlDB queue for jobs and will then run the actual indexing jobs and post back its results for storage in the PurlDB. The code for the scancode.io worker is at https://github.com/nexB/scancode.io/pull/1078

To test this feature:
1. Install ScanCode.io and PurlDB from the respective branches of the PR or the main branch when merged

3. 2. Add one package to the PurlDB using the API. This will create a scan queue entry. This entry will be picked up by the scancode.io worker and be scanned. The scan results will be sent back to the purldb
