### ISSUE TITLE
Packaging and deployment of purldb/matchcode (docker, traefik, etc.)

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#274]
We have multiple databases and apps that need to collaborate to support #224. There is:

- purldb and its database and API endpoints
- matchcode and its database and the new matching endpoint
- matchcode also has direct access to the purldb database for matching

We need a way to have these services to access each others resources and to make the API endpoints of purldb and matchcode available.

Solution 1:

We use traefik to route requests between purldb and matchcode.

For the database, there is a single docker service named `db`, that is brought up by the purldb docker compose. matchcode uses this db service with a different database definition for scancode.io probjects.

TODO:
- [x] Write instructions on how to create shared db between purldb and matchcode and to load a purldb db dump afterwards
- [x] Configure https access using traefik
- [x] Update deployment scripts and services for new matchcode/traefik services
- [ ] #284
- [x] test deployment on staging, esp. https access
- [x] #364

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I would need your help to determine the best structure for the doc

**Comment by JonoYang** [comment]
We have an instance of purldb at public.purldb.io with packages available for browsing at https://public.purldb.io/api/packages

A list of the purldb API endpoints and how to interact with them is available at https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/purldb/rest_api.html

We also have a PurlDB Docker container available at https://github.com/nexB/purldb/pkgs/container/purldb, where it can be downloaded using: `docker pull ghcr.io/nexb/purldb:latest`
