### ISSUE TITLE
PurlDB: Store symbols (from scan results) in the PurlDB

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#323]
We are collecting these in a "symbols" list in source-inspector. These will became stored as JSON in extra data in SCIO and we will keep them as extra data in PURLDB as a start.

**Comment by keshav-space** [comment]
Completed in https://github.com/nexB/purldb/pull/351

The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Go to `/api/collect/` add PURL for indexing. ex: `/api/collect/?purl=pkg:generic/ipkg@0.99.19`
2. Once the indexing has completed got to `/api/resources/`and filter out resource based on PURL to see the symbols for each resource in extra_data field. ex: `/api/resources/?purl=pkg:generic/ipkg@0.99.19`
