### ISSUE TITLE
PurlDB: Collect symbols for arbitrary download URL (API endpoint either as a free standing API or creating a generic or inferred PURL)

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#325]

**Comment by keshav-space** [comment]
Completed in https://github.com/nexB/purldb/pull/351

The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Go to `/api/collect/` add PURL along with `download_url` as a qualifier for indexing. ex: `/api/collect/?purl=pkg:generic/foobar@1.2.3?download_url=<foobar-1.2.3-archive-download-url>`
2. Once the indexing has completed, go to `/api/resources/`and filter out resource based on PURL to see the symbols for each resource in extra_data field. ex: `/api/resources/?purl=pkg:generic/foobar@1.2.3`
