### ISSUE TITLE
PurlDB: purl2sym Packaging and documentation

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#330]
This documentation is part of the standard PurlDB doc.
There is also some documentation that needs to live elsewhere:
- [x] Create documentation for source-inspector https://github.com/nexB/source-inspector?tab=readme-ov-file#to-get-started
- [x] Create documentation for symbols and strings pipelines in SCIO https://github.com/nexB/scancode.io/pull/1198 
- [x] Create documentation for symbols and strings collection in PurlDB https://github.com/nexB/purldb/pull/411

**Comment by keshav-space** [comment]
> [x] Create documentation symbols and strings pipelines in SCIO

Documentation for the `collect_symbols` and `collect_source_strings` pipelines in SCIO are available here: https://scancodeio.readthedocs.io/en/latest/built-in-pipelines.html. For local installation, also refer to this: https://scancodeio.readthedocs.io/en/latest/installation.html#local-development-installation.

**Comment by keshav-space** [comment]
More documentation added in

- https://github.com/nexB/scancode.io/pull/1198
- https://github.com/nexB/purldb/pull/411
- https://github.com/nexB/source-inspector/pull/22

**Comment by keshav-space** [comment]
Docs available at:

- https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/how-to-guides/tutorial_symbol_and_string_collection.html
- https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/purldb/symbol_and_string_collection.html
- https://scancodeio.readthedocs.io/en/latest/tutorial_web_ui_symbol_and_string_collection.html
- https://github.com/nexB/source-inspector/blob/main/README.rst
