### ISSUE TITLE
PurlDB: Provide a list of all known package versions

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#333]
For the generic packages, we we are processing in batches, we want to also return their versions. This is special since many of these are generic packages without structured version metadata.

**Comment by keshav-space** [comment]
Completed in https://github.com/nexB/fetchcode/pull/107, https://github.com/nexB/fetchcode/pull/112, https://github.com/nexB/fetchcode/pull/113, https://github.com/nexB/fetchcode/pull/114 and https://github.com/nexB/fetchcode/pull/115

The simple way to test this is to follow the below steps:

1. Install fetchcode using `pip install fetchcode`
2. Call the fetchcode.package.info using versionless PURL. See example below.

Example to fetch all known version of `pkg:generic/miniupnpc`:
```python
>>> from fetchcode.package import info
>>> packages = list(info("pkg:generic/miniupnpc"))
>>> print("\n".join([p.purl for p in packages]))
pkg:generic/miniupnpc@1.7
pkg:generic/miniupnpc@1.8
pkg:generic/miniupnpc@1.9
pkg:generic/miniupnpc@2.0
pkg:generic/miniupnpc@2.1
pkg:generic/miniupnpc@2.2.0
pkg:generic/miniupnpc@2.2.1
pkg:generic/miniupnpc@2.2.2
pkg:generic/miniupnpc@2.2.3
pkg:generic/miniupnpc@2.2.4
pkg:generic/miniupnpc@2.2.5
pkg:generic/miniupnpc@2.2.6
pkg:generic/miniupnpc@2.2.7


```
