### ISSUE TITLE
PurlDB: Monitor scanning jobs

### ISSUE THREAD

**Issue by DennisClark** [nexB/purldb#334]
We should have a way to check on the status of indexing/scanning jobs in PurlDB, this could be either an API endpoint that provide status on the symbols collections/indexing that are pending for a PURL; or it could a management command.

An API endpoint on the scan_queue would be best.

**Comment by pombredanne** [comment]
@keshav-space I think this is completed now by @JonoYang ... do you mind to add a completion comment?

**Comment by keshav-space** [comment]
Completed in https://github.com/nexB/purldb/pull/290 by @JonoYang 

The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Create a scan queue user using this command `python manage.py purldb-scan-queue-worker` and get API key for user.
2. Now visit `/api/scan_queue/` make sure to provide your API key obtained in step 1 in request header. Ex: `Authorization: Token <your-api-key>`
3. There you can get the `scan_status` for all the package being indexed.

Meaning of various `scan_status`.
```python 
 0 => 'new'  
 1 => 'submitted'  
 2 => 'in progress'  
 3 => 'scanned'  
 4 => 'indexed'  
 5 => 'failed'  
 6 => 'timeout'  
 7 => 'scan index failed'  
```
