### ISSUE TITLE
Create a code matcher for approximate files matching

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#342]
See also:
- [x] https://github.com/nexB/matchcode-toolkit/issues/5

**Comment by JonoYang** [comment]
This has been merged into main. We have created a new table for storing approximate file fingerprints and updated the indexing functions to index those values from scans. We have also updated the fingerprinting functions in scancode-toolkit to also generate fingerprints for text files. With these changes, we now able to perform approximate file matching in the matching pipeline run by matchcode. https://github.com/nexB/purldb/blob/main/matchcode_pipeline/pipelines/matching.py#L109
