### ISSUE TITLE
PurlDB: Integrate d2d analysis in PurlDB

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#373]
Given a package set I would like to trigger the scancode.io d2d mapping pipeline for the packages in the *package set* such that all the packages of the set are validated against all the other in the set based on the "package_content". For instance:
- `binary` mapped to the `released source archive`
- `binary` mapped to the `VCS repo`
- `VCS repo` mapped to `released source archive` (Like seen in the infamous xz issue)

The API could therefore be either:
- a single "binary" PURL with its companion source found with "purl2vcs" 
- a pair of from and to PURLs to run d2d on
- **a package set or one PURL in a set to run the many d2d as explained above**

Since we have a new endpoint in:
- https://github.com/nexB/purldb/pull/404
 
.... We should be able to have a purl CLI to integrate all these together.
- [ ] https://github.com/nexB/purldb/issues/420

**Comment by pombredanne** [comment]
Here are the design I think we can consider, using https://mermaid.live/ 

### 1. Preferred
- [1.Two URLs input and no storage- use PurlDB as API.txt](https://github.com/nexB/purldb/files/15168990/1.Two.URLs.input.and.no.storage-.use.PurlDB.as.API.txt)

![1 Two URLs input and no storage- use PurlDB as API](https://github.com/nexB/purldb/assets/675997/0684b7f2-0d25-4ef5-b4a6-cf3fb2d271d5)


### 2. Other designs

- [URL input and collect PURLs.txt](https://github.com/nexB/purldb/files/15168986/URL.input.and.collect.PURLs.txt)

![URL input and collect PURLs](https://github.com/nexB/purldb/assets/675997/5b5a9023-6ad9-4832-89d6-e5c6c11bd0c9)

- [PURL Input in PurlDB.txt](https://github.com/nexB/purldb/files/15168987/PURL.Input.in.PurlDB.txt)

![PURL Input in PurlDB](https://github.com/nexB/purldb/assets/675997/a9d3d577-b0ae-4ffe-9c94-845a83874f74)

- [PURL Input and all d2d in the set.txt](https://github.com/nexB/purldb/files/15168989/PURL.Input.and.all.d2d.in.the.set.txt)

![PURL Input and all d2d in the set](https://github.com/nexB/purldb/assets/675997/d3776d08-63c1-44b4-8a24-b02e595a3411)

- [Using MatchCode.io.txt](https://github.com/nexB/purldb/files/15168985/Using.MatchCode.io.txt)

![Using MatchCode io](https://github.com/nexB/purldb/assets/675997/12f88041-ae95-4e0d-96ef-9b6e7a968b57)

**Comment by JonoYang** [comment]
@pombredanne 

I went over the design of 1) with @TG1999 and we identified areas of the purldb/scancode.io scan queue system that needs to be modified to implement 1).

1. ScannableURI model changes
    - Handle more than one download url
    - Remove requirement that a ScannableURI has to be related to a Package
        - This is needed for 1) since there is no related Package when we are giving the purldb api two download urls
    - Update related functions to reflect model changes
2. minecode API changes
    - the `get_next_download_url` endpoint needs to be updated to something like `get_next_job`, and the data returned from that endpoint should have a list of download urls to be scanned or worked on, the list of pipelines to be run, and the uuid of the scannableuri for that request 
    - Need to figure out how to send the d2d results back to the user after the project is done running
3. scancode.io changes
    - The scan queue worker command on scancode.io and the functions to get the next download url from purldb needs to be updated to reflect changes made to the `get_next_download_url` endpoint
