### ISSUE TITLE
Extract source symbols and strings using Pygments

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#399]
This implies:
- [x] Support in source-inspector https://github.com/nexB/source-inspector/pull/20
- [x] Create add-on pipeline in SCIO for Pygments source symbols https://github.com/nexB/scancode.io/pull/1179

**Comment by pombredanne** [comment]
See https://github.com/nexB/source-inspector/pull/20

**Comment by keshav-space** [comment]
The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Go to `/api/collect/` add PURL for indexing. ex: `/api/collect/?purl=pkg:generic/udhcp@0.9.7&addon_pipelines=collect_pygments_symbols`
2. Once the indexing has completed go to `/api/resources/`and filter out resource based on PURL to see the symbols and strings for each resource in extra_data field. ex: `/api/resources/?purl=pkg:generic/udhcp@0.9.7`
