### ISSUE TITLE
Extend PURL Scan API endpoint to run another second code scanning tool, for virus detection with clamav

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#401]
Given a PURL, this is about scanning code for virus with clamav. This will be exposed in the purldb
- [x] https://github.com/nexB/scancode.io/issues/1182
- [x] https://github.com/nexB/purldb/issues/443

**Comment by keshav-space** [comment]
Completed in:
- https://github.com/nexB/scancode.io/pull/1193
- https://github.com/nexB/scancode.io/pull/1250
- https://github.com/nexB/purldb/pull/452

The simple way to test this is to follow the below steps after installing PurlDB (https://github.com/nexB/purldb?tab=readme-ov-file#installation):

1. Go to `/api/collect/` add PURL for indexing. ex: `/api/collect/?purl=pkg:gnu/libiconv@1.17&addon_pipelines=scan_for_virus`
2. Once the indexing has completed go to `/api/resources/`and filter out resource based on PURL to see the `virus_report` for malicious resource in `extra_data` field. ex: `/api/resources/?purl=pkg:gnu/libiconv@1.17`
