### ISSUE TITLE
Ensure that "purl2vcs" is called during the PurlDB data collection in /collect

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#418]
Beyond the command line "improver" we have, I would like to ensure that "purl2vcs" is called during the PurlDB data collection in /collect so that we get the Git sources package indexed too.

**Comment by pombredanne** [comment]
As an example: https://github.com/winstonjs/winston/ and https://www.npmjs.com/package/winston

Say we call collect/ with this PURL `pkg:npm/winston3.13.0`
I would like this PURL to be found, added and also collected/indexed:
`pkg:github/winstonjs/winston@v3.13.0`

**Comment by TG1999** [comment]
This is done now.

This PR has been merged

https://github.com/nexB/purldb/pull/428
To test this feature:

Install PurlDB from the main branch
Run
make dev
make run

Make a request to /api/collect?purl=pkg:npm/express@4.18.1

After making the request you can see the "package_sets", click on the package in "packages", and you will find the "source_repo" package associated with the "source_archive" package.

![Screenshot from 2024-05-24 12-35-53](https://github.com/nexB/purldb/assets/34160672/e0318095-5e5a-4f54-a562-d28b9db8c13f)
![Screenshot from 2024-05-24 12-35-39](https://github.com/nexB/purldb/assets/34160672/e36556fd-7365-4604-9b9a-3b22d1cf4bd1)
