### ISSUE TITLE
Deploy purl2sym in PurlDB release

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#425]
- [x] update changelog for purl2sym https://github.com/nexB/purldb/pull/411/commits/7db678c90bdd1be695a2e77ff496f0be2534a0be
- [x] Tag release
- [x] Create a PurlDB data dump with purl2sym symbols from the collected Batches (nice to have)

**Comment by keshav-space** [comment]
New release with purl2sym is available here https://github.com/nexB/purldb/releases/tag/v5.0.0. We also have small data dump with symbols and strings for the latest versions of packages in Batch 1-5.
