### ISSUE TITLE
Error in installing while running (make dev)

### ISSUE THREAD

**Issue by Sahajj** [nexB/purldb#44]
When deploying PurlDb in Ubuntu 22.04.2 LTS, make dev encountered an error.

The configuration with the error is shown here.

> 
>   error: subprocess-exited-with-error
>   
>   × Running setup.py install for psycopg2 did not run successfully.
>   │ exit code: 1

**A text file with the error outputs is appended.**
  

[Error_in__make_dev.TXT](https://github.com/nexB/purldb/files/10848927/Error_in__make_dev.TXT)

**Comment by 35C4n0r** [comment]
@JonoYang @pombredanne i was able to reproduce this on Ubuntu-22 and Ubuntu-20, we need to add `sudo apt install libpq-dev` to the installation and also update https://scancode-toolkit.readthedocs.io/en/stable/getting-started/install.html#prerequisites 
as `python-dev` dosen't exists anymore.
@Sahajj for now run `sudo apt install libpq-dev` and then run `make dev` again.

**Comment by JonoYang** [comment]
@Sahajj Go ahead!

**Comment by Sahajj** [comment]
@JonoYang Done can you review #45
