### ISSUE TITLE
Automate the publishing of PurlDB container images on tag

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#444]

**Comment by tdruez** [comment]
@JonoYang @pombredanne Implemented in https://github.com/nexB/purldb/pull/447

**Comment by tdruez** [comment]
"Publish Docker image on GHCR" workflow merged https://github.com/nexB/purldb/pull/447
This will be triggered on each new tag.
I've triggered a run so we have a container image available at https://github.com/nexB/purldb/pkgs/container/purldb
