### ISSUE TITLE
purl2all: Create doc for PURL services accessible through the API

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#445]
We want to make sure that:
- [x] Ensure that the latest PurlDB API deployed 
  -  This also provides the API documentation

**Comment by JonoYang** [comment]
Pages we'll need:
- [ ] Installation
  - [ ] PurlDB
    - [ ] Package scan worker
  - [ ] MatchCode.io
- [ ] Overview of API endpoints and examples on how to communicate with it
  - [ ] packages
  - [ ] update_packages
  - [ ] package_sets
  - [ ] resources
  - [ ] approximate_directory_content_index
    - This will be deprecated
  - [ ] approximate_directory_structure_index
    - This will be deprecated
  - [ ] exact_file_index
    - This will be deprecated
  - [ ] exact_package_archive_index
    - This will be deprecated
  - [ ] cditems
    - This will be deprecated
  - [ ] on_demand_queue
  - [ ] validate
  - [ ] collect
  - [ ] watch
  - [ ] scan_queue
- [ ] MatchCode.io matching #241

**Comment by pombredanne** [comment]
For reference the API doc is at https://public.purldb.io/api/docs/

**Comment by JonoYang** [comment]
@pombredanne I am removing some API endpoints that we don't need in #453

**Comment by pombredanne** [comment]
This is completed and available at https://public.purldb.io/api/docs/

**Comment by pombredanne** [comment]
Actually @keshav-space can you add doc on the purlwatch feature?

**Comment by pombredanne** [comment]
See https://github.com/nexB/purldb/issues/474 for a follow up
