### ISSUE TITLE
Dead link to documentation

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#491]
there is a dead link present in a few places : https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/how-to-guides/tutorial_symbol_and_string_collection.html

See https://github.com/search?q=org%3AnexB+tutorial_symbol_and_string_collection.html&type=issues

May be we could have redirect for these?

**Comment by keshav-space** [comment]
Done. We're now redirecting https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/how-to-guides/tutorial_symbol_and_string_collection.html to https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/how-to-guides/symbols_and_strings.html.
