### ISSUE TITLE
Enhance package data from scan summary results

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#83]
When we process a package scan from scancode.io, we only index the resource data and directory fingerprints. We should use the scan summary results to enhance the Package data of the Package the scan is for. For example, if we are missing a license or copyright on a package, then we should take the license and holder from the scan summary and use those values.

**Comment by pombredanne** [comment]
We are now enhancing the stored data for a package using the scans and the scan summary. Closing as done.
