### ISSUE TITLE
Do not walk parent POMs all the way up

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#85]
For instance this https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.66.Final/netty-codec-http-4.1.66.Final.pom has these parents chain:
- https://repo1.maven.org/maven2/io/netty/netty-parent/4.1.66.Final/netty-parent-4.1.66.Final.pom
- https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
we should ignore and stop walking up the ancestry when hitting `org/sonatype/oss/oss-parent` (and possibly some others TBD) as this otherwise injects incorrect data in the children

```
<parent>
<groupId>org.sonatype.oss</groupId>
<artifactId>oss-parent</artifactId>
<version>9</version>
</parent>
```

**Comment by pombredanne** [comment]
Another example https://repo1.maven.org/maven2/org/apache/logging/logging-parent/9/logging-parent-9.pom
The idea of @JonoYang to stop recursing up when the groupid of the parent is no longer a proper suffix if the child group if may work.
Otherwise we could just create a list of ignored POM PURLs (ignoring version)

**Comment by JonoYang** [comment]
When we are using data from an ancestor pom, we only use data from ancestors whose groupid is in the groupid of the package we're looking at. We now also log whenever an ancestor pom was not used when creating the package data.
