### ISSUE TITLE
Determine a corresponding source repo(s) (such as Git) for a binary that does not have one obvious

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#90]
Sometimes we have a package that does not have sources or does not have a corresponding source repo (such as a git repo).
We should be able to infer a source repo and possibly a tag or release in this repo based on other available metadata:
- the homepage may be for a GitHub or GitLab repo or some other field
- for instance a description (seen in NuGet packages) or a README may have a GitHub link

We could also infer the tag based on a version, with or without V prefix.

**Comment by pombredanne** [comment]
@TG1999 ping FYI. We may need this for Maven, npm and NuGet

**Comment by TG1999** [comment]
Done in https://github.com/nexB/purldb/pull/137
